language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: python runtests.py 
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
