"""Added campaign model

Revision ID: 11fb55be6e62
Revises: 155bdd6d893d
Create Date: 2013-12-23 15:37:54.560976

"""

# revision identifiers, used by Alembic.
revision = '11fb55be6e62'
down_revision = '155bdd6d893d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('send_newsletter', sa.Boolean(), nullable=False, server_default=sa.text(u"'t'")))

    op.alter_column('user', 'send_newsletter', server_default=None)

    # Create a new table for email_campaign
    op.create_table('email_campaign',
        sa.Column('id', sa.Integer, nullable=False, primary_key=True),
        sa.Column('event_id', sa.Integer, nullable=False),
        sa.Column('start_datetime', sa.DateTime, nullable=False),
        sa.Column('end_datetime', sa.DateTime, nullable=True),
        sa.Column('name', sa.Unicode(250), nullable=False, unique=True),
        sa.Column('title', sa.Unicode(250), nullable=False),
        sa.Column('created_at', sa.DateTime, nullable=False),
        sa.Column('updated_at', sa.DateTime, nullable=False),
    )
    op.create_foreign_key("fk_email_campaign_event_id", "email_campaign", "event", ["event_id"], ["id"], ondelete="CASCADE")

    # Create a new table for email_campaign_user
    op.create_table('email_campaign_user',
        sa.Column('id', sa.Integer, nullable=False, primary_key=True),
        sa.Column('user_id', sa.Integer, nullable=False),
        sa.Column('email_campaign_id', sa.Integer, nullable=False),
        sa.Column('created_at', sa.DateTime, nullable=False),
        sa.Column('updated_at', sa.DateTime, nullable=False),
    )
    op.create_foreign_key("fk_email_campaign_user_user_id", "email_campaign_user", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("fk_email_campaign_user_email_campaign_id", "email_campaign_user", "email_campaign", ["email_campaign_id"], ["id"], ondelete="CASCADE")

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'send_newsletter')
    op.drop_table('email_campaign_user')
    op.drop_table('email_campaign')
    ### end Alembic commands ###
