"""Initial

Revision ID: 2625cb1e8798
Revises: None
Create Date: 2012-09-27 07:03:26.562731

"""

# revision identifiers, used by Alembic.
revision = '2625cb1e8798'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votespace',
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentspace',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('userid', sa.Unicode(length=22), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('user',
    sa.Column('userid', sa.String(length=22), nullable=False),
    sa.Column('username', sa.Unicode(length=80), nullable=True),
    sa.Column('fullname', sa.Unicode(length=80), nullable=False),
    sa.Column('lastuser_token', sa.String(length=22), nullable=True),
    sa.Column('lastuser_token_type', sa.Unicode(length=250), nullable=True),
    sa.Column('lastuser_token_scope', sa.Unicode(length=250), nullable=True),
    sa.Column('email', sa.Unicode(length=80), nullable=True),
    sa.Column('phone_no', sa.Unicode(length=15), nullable=True),
    sa.Column('job_title', sa.Unicode(length=120), nullable=True),
    sa.Column('company', sa.Unicode(length=1200), nullable=True),
    sa.Column('userinfo', sa.UnicodeText(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lastuser_token'),
    sa.UniqueConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('commentspace_id', sa.Integer(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_html', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('votes_id', sa.Integer(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commentspace_id'], ['commentspace.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['votes_id'], ['votespace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id','commentspace_id')
    )
    op.create_table('venue',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('address1', sa.Unicode(length=80), nullable=False),
    sa.Column('address2', sa.Unicode(length=80), nullable=False),
    sa.Column('city', sa.Unicode(length=30), nullable=False),
    sa.Column('state', sa.Unicode(length=30), nullable=False),
    sa.Column('postcode', sa.Unicode(length=20), nullable=False),
    sa.Column('country', sa.Unicode(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('votespace_id', sa.Integer(), nullable=False),
    sa.Column('votedown', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['votespace_id'], ['votespace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id','votespace_id')
    )
    op.create_table('event',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('blurb', sa.Unicode(length=250), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('maximum_participants', sa.Integer(), nullable=False),
    sa.Column('website', sa.Unicode(length=250), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Unicode(length=250), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','profile_id')
    )
    op.create_table('sponsor',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('website', sa.Unicode(length=250), nullable=True),
    sa.Column('image_url', sa.Unicode(length=250), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','event_id')
    )
    op.create_table('participant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('mentor', sa.Boolean(), nullable=False),
    sa.Column('reason_to_join', sa.UnicodeText(), nullable=False),
    sa.Column('email', sa.Unicode(length=80), nullable=False),
    sa.Column('phone_no', sa.Unicode(length=15), nullable=False),
    sa.Column('job_title', sa.Unicode(length=120), nullable=False),
    sa.Column('company', sa.Unicode(length=1200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('blurb', sa.Unicode(length=250), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('maximum_size', sa.Integer(), nullable=False),
    sa.Column('participating', sa.Boolean(), nullable=False),
    sa.Column('votes_id', sa.Integer(), nullable=False),
    sa.Column('comments_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comments_id'], ['commentspace.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['votes_id'], ['votespace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id','event_id')
    )
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('role', sa.Unicode(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id','participant_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_member')
    op.drop_table('project')
    op.drop_table('participant')
    op.drop_table('sponsor')
    op.drop_table('event')
    op.drop_table('vote')
    op.drop_table('venue')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('profile')
    op.drop_table('commentspace')
    op.drop_table('votespace')
    ### end Alembic commands ###
