"""Added payment model

Revision ID: 38bc5fa8b6d6
Revises: 155bdd6d893d
Create Date: 2013-12-23 19:35:00.124877

"""

# revision identifiers, used by Alembic.
revision = '38bc5fa8b6d6'
down_revision = '155bdd6d893d'

from alembic import op
from coaster.sqlalchemy import JsonDict
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateway_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('server_response', JsonDict(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column(u'event', sa.Column('currency', sa.Unicode(length=3), nullable=True))
    op.add_column(u'event', sa.Column('payment_credentials', sa.Unicode(length=100), nullable=True))
    op.add_column(u'event', sa.Column('payment_service', sa.Unicode(length=100), nullable=True))

    op.add_column(u'event', sa.Column('purchased_ticket', sa.Boolean(), nullable=False, server_default=sa.text(u"'f'")))
    op.alter_column(u'event', 'purchased_ticket', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'event', 'payment_service')
    op.drop_column(u'event', 'payment_credentials')
    op.drop_column(u'event', 'currency')
    op.drop_table('payment_gateway_log')
    ### end Alembic commands ###
