"""Added skill level

Revision ID: 44b1b3317015
Revises: 2625cb1e8798
Create Date: 2012-09-27 07:15:42.253582

"""

# revision identifiers, used by Alembic.
revision = '44b1b3317015'
down_revision = '2625cb1e8798'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('skill_level', sa.Unicode(length=120), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'skill_level')
    ### end Alembic commands ###
